[RADIO]
center_freq = 2400000000.0
sample_rate = 15000000.0
rx_gain = 74
tx_gain = 70
uhd_id = "None"

[ATTACK]
file = "test"                   # The file name of the packet to be used is located
dataset = "signal_1"            # The dataset name of the packet to be used
repeat = 5                      # The number of times the replay signal will repeat
interval = 1.0                  # The waittime before another packet will be sent

[MONITOR]
threshold = 0.6                 # The value a signal must be above to be considered a packet
cutoff = 100                    # The number of indexes before a packet will be considered ended.
packet_slack = 100              # The number of indexes that will be added to the beginning and ending of the discovered packet
queue_size = 170                 # The 
file_name = "testy"
max_loops = "None"











# center_frequncy: 2.4 GHz -> 2400000000.0

# center_frequency: 915 MHz -> 915000000.0
# sample_rate:      15 MHz