[RADIO]
center_freq = 915000000.0
sample_rate = 15000000.0
rx_gain = 74
tx_gain = 70
uhd_id = "None"

[ATTACK]
file = "test"                   # The file name of the packet to be used is located
dataset = "signal_1"            # The dataset name of the packet to be used
repeat = 5                      # The number of times the replay signal will repeat
interval = 1.0                  # The waittime before another packet will be sent

[MONITOR]
min_packet_size = 250           # Determins how many index's need to be above the threshold to not be thrown out.
threshold = 50.0                # The value a signal must be above to be considered a packet
cutoff = 100                    # The number of indexes before a packet will be considered ended.

max_count = 10000000            #? what was this...
listen_time = 0.3               #? what was this...
pool_size = 3                   # number of processes running packet_detect #! May not use if one process is fast enough











# center_frequncy: 2.4 GHz -> 2400000000.0

# center_frequency: 915 MHz -> 915000000.0
# sample_rate:      15 MHz