[RADIO]
center_freq = 915000000.0
sample_rate = 15000000.0
rx_gain = 74
tx_gain = 70
uhd_id = "None"

[ATTACK]
file = "test"
dataset = "test1"
repeat = 5
interval = 1.0 # in seconds

[MONITOR]
target_freq = 915000000.0
listen_time = 0.3 # in seconds
pool_size = 3
max_count = 10000000

# center_frequncy: 2.4 GHz -> 2400000000.0

# center_frequency: 915 MHz -> 915000000.0
# sample_rate:      15 MHz